# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('game_id', models.CharField(max_length=10, unique=True)),
                ('home_team', models.CharField(max_length=3)),
                ('away_team', models.CharField(max_length=3)),
                ('home_points', models.IntegerField(blank=True, null=True)),
                ('away_points', models.IntegerField(blank=True, null=True)),
                ('highlights', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
